title: arfro
description: > # this means to ignore newlines until "baseurl:"
  Scala functional programming on a run.
permalink: ':title/'
url: "arfro.github.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: annette # add your name
author-img: annette2.jpg # add your photo
about-author: Scala backend engineer on a run - taking time in descovering the nitty gritty details of functional programming.
social-github: arfro # add your Github handle
social-linkedin: annetteres # add your Linkedin handle
social-email: aerfromenes@gmail.com # add your Email address

# Disqus
discus-identifier: arfro # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
